### ISSUE TITLE
Part 2 - Checklist ticket

### ISSUE THREAD

**Issue by adamva** [CMPUT-404-2023-Not-Found/CMPUT404-project-socialdistribution#215]
- [x] Link to OpenAPI detailing the API's spec
- [x] Valid account credentials for using the app
- [x] Example cURL command that interacts with API
- [x] Proof of other group collaboration & their endpoints we integrated with

[Shared Google Drive](https://drive.google.com/drive/folders/10ixCBeg9i1Rve7O1_XyjjkxashuZhwmQ?usp=sharing) Folder for screenshots & other resources (Switch to Ualberta Google Account for access)
