### ISSUE TITLE
EPIC (Nice To Have): CICD Setup

### ISSUE THREAD

**Issue by adamva** [CMPUT-404-2023-Not-Found/CMPUT404-project-socialdistribution#96]
- [ ] When a ticket is created, it is placed in Todo column
- [ ] When a ticket has a branch created, the ticket moves to In Progress column
- [ ] When a ticket branch has a PR that goes from ticket branch to dev, the ticket is moved to QA column
- [ ] When a ticket branch has a PR that goes from dev to master, the ticket is moved to Done
- [ ] When a PR is made from ticket branch to dev, the dev branch is deployed to the dev Heroku instance
- [ ] After deployment to the dev Heroku instance, tests are run against it
- [ ] When a PR is made from dev to master, the master branch is deployed to the master Heroku instance
- [ ] After deployment to the master Heroku instance, tests are run against it
